// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  docsSidebar: [
    'overview',
    {
      type: 'category',
      label: 'Platform Areas',
      link: {
        type: 'generated-index',
        title: 'Platform Areas',
        description: 'Customer-facing guides for the main QuilrAI product areas.',
      },
      customProps: {
        icon: 'Layers',
      },
      items: [{type: 'autogenerated', dirName: 'platform-areas'}],
    },
    {
      type: 'category',
      label: 'Customer Support',
      link: {
        type: 'generated-index',
        title: 'Customer Support',
        description: 'Guide for customers filing and managing support tickets with Quilr AI.',
      },
      customProps: {
        icon: 'Handshake',
      },
      items: [{type: 'autogenerated', dirName: 'customer support'}],
    },
    {
      type: 'doc',
      id: 'release-notes/index',
      label: 'Release Notes',
      customProps: {
        icon: 'Newspaper',
      },
    },
  ],
};

export default sidebars;
