/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "QuilrAI Platform Docs",
  "tagline": "Customer-facing documentation for the QuilrAI platform",
  "favicon": "img/favicon.ico",
  "future": {
    "v4": {
      "removeLegacyPostBuildHeadAttribute": true,
      "useCssCascadeLayers": true
    },
    "experimental_faster": {
      "swcJsLoader": false,
      "swcJsMinimizer": false,
      "swcHtmlMinimizer": false,
      "lightningCssMinimizer": false,
      "mdxCrossCompilerCache": false,
      "rspackBundler": false,
      "rspackPersistentCache": false,
      "ssgWorkerThreads": false
    },
    "experimental_storage": {
      "type": "localStorage",
      "namespace": false
    },
    "experimental_router": "browser"
  },
  "url": "https://platform-docs.quilrai.dev",
  "baseUrl": "/",
  "organizationName": "quilrai",
  "projectName": "platform-docs",
  "trailingSlash": false,
  "onBrokenLinks": "throw",
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "markdown": {
    "mermaid": true,
    "format": "mdx",
    "emoji": true,
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    },
    "anchors": {
      "maintainCase": false
    },
    "hooks": {
      "onBrokenMarkdownLinks": "warn",
      "onBrokenMarkdownImages": "throw"
    }
  },
  "themes": [
    "@docusaurus/theme-mermaid",
    [
      "@easyops-cn/docusaurus-search-local",
      {
        "hashed": true,
        "language": [
          "en"
        ],
        "indexDocs": true,
        "indexBlog": false,
        "indexPages": false,
        "docsRouteBasePath": "/",
        "explicitSearchResultPath": true,
        "searchBarShortcut": true,
        "searchBarShortcutHint": true
      }
    ]
  ],
  "plugins": [
    "./plugins/doc-page-markdown.js"
  ],
  "presets": [
    [
      "classic",
      {
        "docs": {
          "routeBasePath": "/",
          "sidebarPath": "./sidebars.js"
        },
        "blog": false,
        "sitemap": {
          "filename": "sitemap.xml",
          "ignorePatterns": [
            "/search"
          ],
          "lastmod": null
        },
        "theme": {
          "customCss": "./src/css/custom.css"
        }
      }
    ]
  ],
  "themeConfig": {
    "image": "img/QuilrAi-Open-Graph.png",
    "colorMode": {
      "defaultMode": "light",
      "respectPrefersColorScheme": true,
      "disableSwitch": false
    },
    "navbar": {
      "title": "",
      "logo": {
        "alt": "QuilrAI",
        "src": "img/QuilrAI-light.png",
        "srcDark": "img/QuilrAI-dark.png"
      },
      "items": [
        {
          "type": "docSidebar",
          "sidebarId": "docsSidebar",
          "position": "left",
          "label": "Platform Docs"
        },
        {
          "href": "https://www.quilr.ai/resources",
          "label": "Resources",
          "position": "right",
          "target": "_blank",
          "rel": "noopener noreferrer"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "links": [
        {
          "title": "Docs",
          "items": [
            {
              "label": "Platform Docs",
              "to": "/"
            },
            {
              "label": "Resources",
              "href": "https://www.quilr.ai/resources",
              "target": "_blank",
              "rel": "noopener noreferrer"
            }
          ]
        }
      ],
      "copyright": "Copyright © 2026 QuilrAI. Built with Docusaurus.",
      "style": "light"
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#3f3f46",
          "backgroundColor": "#ebe1cf"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#a1a1aa",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "color": "#a1a1aa"
            }
          },
          {
            "types": [
              "string",
              "char",
              "attr-value",
              "inserted"
            ],
            "style": {
              "color": "#059669"
            }
          },
          {
            "types": [
              "number",
              "boolean",
              "constant"
            ],
            "style": {
              "color": "#d97706"
            }
          },
          {
            "types": [
              "keyword",
              "atrule",
              "rule",
              "important"
            ],
            "style": {
              "color": "#7c3aed"
            }
          },
          {
            "types": [
              "function",
              "function-variable"
            ],
            "style": {
              "color": "#2563eb"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "property"
            ],
            "style": {
              "color": "#0891b2"
            }
          },
          {
            "types": [
              "class-name",
              "symbol",
              "attr-name"
            ],
            "style": {
              "color": "#ca8a04"
            }
          },
          {
            "types": [
              "regex"
            ],
            "style": {
              "color": "#db2777"
            }
          },
          {
            "types": [
              "operator",
              "arrow",
              "spread",
              "punctuation"
            ],
            "style": {
              "color": "#71717a"
            }
          },
          {
            "types": [
              "variable",
              "maybe-class-name"
            ],
            "style": {
              "color": "#3f3f46"
            }
          },
          {
            "types": [
              "builtin",
              "entity"
            ],
            "style": {
              "color": "#dc2626"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "#ef4444"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "#0d9488"
            }
          },
          {
            "types": [
              "url"
            ],
            "style": {
              "color": "#059669"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#d4d4d8",
          "backgroundColor": "#1f232a"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#71717a",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "color": "#71717a"
            }
          },
          {
            "types": [
              "string",
              "char",
              "attr-value",
              "inserted"
            ],
            "style": {
              "color": "#34d399"
            }
          },
          {
            "types": [
              "number",
              "boolean",
              "constant"
            ],
            "style": {
              "color": "#fbbf24"
            }
          },
          {
            "types": [
              "keyword",
              "atrule",
              "rule",
              "important"
            ],
            "style": {
              "color": "#a78bfa"
            }
          },
          {
            "types": [
              "function",
              "function-variable"
            ],
            "style": {
              "color": "#60a5fa"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "property"
            ],
            "style": {
              "color": "#22d3ee"
            }
          },
          {
            "types": [
              "class-name",
              "symbol",
              "attr-name"
            ],
            "style": {
              "color": "#facc15"
            }
          },
          {
            "types": [
              "regex"
            ],
            "style": {
              "color": "#f472b6"
            }
          },
          {
            "types": [
              "operator",
              "arrow",
              "spread",
              "punctuation"
            ],
            "style": {
              "color": "#a1a1aa"
            }
          },
          {
            "types": [
              "variable",
              "maybe-class-name"
            ],
            "style": {
              "color": "#d4d4d8"
            }
          },
          {
            "types": [
              "builtin",
              "entity"
            ],
            "style": {
              "color": "#f87171"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "#ef4444"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "#2dd4bf"
            }
          },
          {
            "types": [
              "url"
            ],
            "style": {
              "color": "#34d399"
            }
          }
        ]
      },
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        },
        {
          "className": "code-block-diff-add-line",
          "line": "diff-add"
        },
        {
          "className": "code-block-diff-remove-line",
          "line": "diff-remove"
        }
      ],
      "additionalLanguages": []
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "blog": {
      "sidebar": {
        "groupByYear": true
      }
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    },
    "mermaid": {
      "theme": {
        "dark": "dark",
        "light": "default"
      },
      "options": {}
    }
  },
  "baseUrlIssueBanner": true,
  "onBrokenAnchors": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false
};
